### ISSUE TITLE
Crear script para inicializar localmente el proyecto

### ISSUE THREAD

**Issue by gianfranco-s** [guillermo-k/App_restaurant#13]
Luego de cerrar el issue #3 

Realizar el script para que pueda ser corrido en Linux o Windows.
¿Tal vez incorporar WSL?

Debería
1. Iniciar MySQL server
2. Iniciar Apache Web Server
3. Correr el proyecto de Flask

Investigar si es realmente necesario.

**Comment by guillermo-k** [comment]
Con lo del .sh me matas, no ubico, imagino que ha de ser un tipo de ejecutable que haria como si uno escribe el comando por consola, si es asi, en windows funciona ese .sh?

**Comment by gianfranco-s** [comment]
Lo que podemos hacer con este issue, es que vos des la solución para Windows, y yo doy la solución para Linux

**Comment by guillermo-k** [comment]
Yo quisiera ver si hay una solucion que sirva para los 2 sistemas, para que sea una app y listo, que no dependa del SO, tal vez, si se puede "consulta" desde el script que SO usa la PC y con un condicional ejecutar una u otra solucion

**Comment by gianfranco-s** [comment]
Un script de python te lo hace divinamente. ¿Te querés asignar el issue?

**Comment by gianfranco-s** [comment]
Finalmente nos dimos cuenta que no se requerían acciones adicionales para iniciar el proyecto.
