### ISSUE TITLE
No es posible cargar usuarios

### ISSUE THREAD

**Issue by gianfranco-s** [guillermo-k/App_restaurant#21]
En el front end, cuando quiero cargar un usuario, obtengo este error:
![image](https://user-images.githubusercontent.com/69116761/167265316-71e4eb23-1a6b-4e2f-ae65-b0417b314e27.png)

**Comment by gianfranco-s** [comment]
@guillermo-k , me parece mejor, en vez de cambiar en el front, cambiar en el back, que las rutas terminen sin `/`

Entonces, en `app.py` podríamos cambiar
`/crear_usuario/` por `/crear_usuario`
Y
`/modificar_usuario/` por `/modificar_usuario`

**Comment by gianfranco-s** [comment]
@guillermo-k tengo algunas ideas para solucionar este issue. ¿Me lo puedo asignar?

**Comment by guillermo-k** [comment]
Sigue fallando? Pensé que ya lo había solucionado.
Ahí, creo que me habías hecho el comentario de cambiarlo en el back
No te lo podes auto-asignar?

**Comment by gianfranco-s** [comment]
Ahí revisé de vuelta, ya está solucionado.
Me lo puedo auto-asignar, pero quería preguntarte antes.
