### ISSUE TITLE
Cuando en la pantalla de login se pone una cantidad diferente a 5, no se muestran las mesas adicionales

### ISSUE THREAD

**Issue by gianfranco-s** [guillermo-k/App_restaurant#24]
Pero sí aparece reflejado el cambio cuando la cantidad de mesas es menor.

**Comment by guillermo-k** [comment]
Encontré el problema, muestra como máximo la cantidad de mesas creadas previamente, si en algún momento se han creado (desde administrar/cantidad de mesas). Se van a mostrar sin inconveniente.
Esto se debe a que modificar la cantidad de mesas desde el inicio, no crea mesas nuevas en la DB

**Comment by guillermo-k** [comment]
Lo corrijo una vez cerrado #7 que seguro generara conflictos
