### ISSUE TITLE
Agregar categoria a los platos

### ISSUE THREAD

**Issue by guillermo-k** [guillermo-k/App_restaurant#32]
Agregar una categoría a los platos, para agruparlos por esta en el menú:
Ejemplo:

----Bebidas:
--------Coca 600cc.
--------Agua con gas.
--------Etc.
----Pizas:
--------Calabresa.
--------Muzzarela.

**Comment by gianfranco-s** [comment]
Esto nos va a requerir aprender a hacer migraciones en Flask.

**Comment by gianfranco-s** [comment]
Otra manera de hacerlo, sería usando tags:
Coca 600cc -- Tags: `Bebida` `Sin gas`

No me parece excelente idea, pero es una posibilidad

**Comment by guillermo-k** [comment]
> Esto nos va a requerir aprender a hacer migraciones en Flask, si es que cada "fila" tendrá asociada la categoría a la que pertenece el plato.

No entiendo bien a que te referís.
Yo veo 2 maneras de hacerlo: en ambas, se agrega el campo categoría al plato. Y con esta se clasifican los mismos.
1- Se ingresa la categoría manualmente(la cual no me gusta porque da lugar a errores de tipeo, donde Bebidas!=bebidas)
2- Se crea una tabla **categorias** y la categoria del plato es FOREIGN KEY de **categorias**
