### ISSUE TITLE
TypeError al borrar un plato sin imagen

### ISSUE THREAD

**Issue by gianfranco-s** [guillermo-k/App_restaurant#38]
Dijo guillermo-k

"Si podes, fíjate cómo se puede solucionar lo del except de la línea 234. Si pongo except: me lo marca el flake, y con except exceptions: falla"

**Comment by guillermo-k** [comment]
El error aparece al intentar borrar cualquier plato, tenga o no foto.
El problema esta en el (except)

**Comment by gianfranco-s** [comment]
Solucionado
