### ISSUE TITLE
Actualizar metodología de ingreso de datos

### ISSUE THREAD

**Issue by gianfranco-s** [guillermo-k/App_restaurant#46]
Para poder modificar los pedidos, hay que ir a Administración -> Cantidad de mesas -> Seleccione la cantidad de mesas -> Enviar

Parece redundante, ya que al loguearse, se indicó ya la cantidad de mesas.

**Comment by guillermo-k** [comment]
Si te entiendo bien, estarías diciendo de eliminar el sub-menú CANTIDAD DE MESAS. Yo considero que debe quedar la posibilidad de modificar dicho valor, si por algún motivo se necesita agregar o quitar alguna mesa, no es lógico que el usuario deba desloguearse y volver a loguearse para hacerlo

**Comment by gianfranco-s** [comment]
Es verdad. ¿Pero no podría estar únicamente en el menú de administración?

El comportamiento podría ser así:
`global cantidad_mesas_inicial = 5`

Luego, si el usuario lo desea, que modifique `cantidad_de_mesas` en el menú correspondiente.

**Comment by guillermo-k** [comment]
Si, no es para nada necesario que este en la vista de login, y para sacarlo, solo habría que borrar el input con su respectivo label del html, y 2 líneas en app.py. Es mas, en un principio lo había puesto solo en administración. Pero me pareció que estaba bueno, poderlo modificar al hacer el login, y no tener que buscar la opción en administración cada vez que se inicia la app

**Comment by guillermo-k** [comment]
@gianfranco-s Que opinas de crear una cookie que almacene el ultimo valor que se le dio a cantidad_mesas, y que al iniciar la app, fije ese valor?

**Comment by gianfranco-s** [comment]
@guillermo-k excelente! 

> Si, no es para nada necesario que este en la vista de login, y para sacarlo, solo habría que borrar el input con su respectivo label del html, y 2 líneas en app.py. Es mas, en un principio lo había puesto solo en administración. Pero me pareció que estaba bueno, poderlo modificar al hacer el login, y no tener que buscar la opción en administración cada vez que se inicia la app

En conjunto con tu propuesta de la cookie, el comportamiento final podría ser algo así:
`cantidad_mesas_inicial = 5  # variable usada por única vez, para el inicio del programa`

Se genera la cookie al salir, para decidir cuántas son las mesas que se mostrarán la próxima vez. Si no está presente, por el motivo que sea, se vuelve a usar `cantidad_mesas_inicial`

**Comment by guillermo-k** [comment]
Te parece usar una variable extra?
'''cantidad_mesas = 5
If cookie != None:
    cantidad_mesas = int(cookie)
"""
Y después, fuera de borrar el input y demás, agregar el seteo de la cookie quedaría todo igual

**Comment by gianfranco-s** [comment]
Hice merge, pero cuando fui a correr el proyecto nuevamente, salió este error:
![image](https://user-images.githubusercontent.com/69116761/168450036-b1be20b8-ffd6-49b0-9e6e-df850a88cd29.png)

Corrí el comando
```git reset --hard <último commit que anduvo>```

Y ahora anda nuevamente. Te asigno el issue para ver qué pasó.

**Comment by gianfranco-s** [comment]
Solucionado con [PR #60](https://github.com/guillermo-k/App_restaurant/pull/60)
