### ISSUE TITLE
app - largo de líneas

### ISSUE THREAD

**Issue by gianfranco-s** [guillermo-k/App_restaurant#9]
Consultar la [guía de estilos PEP8](https://peps.python.org/pep-0008/), para determinar la cantidad máxima de caracteres que pueden haber en una línea.

Modificar el código de manera acorde.

**Comment by gianfranco-s** [comment]
Este issue puede considerarse resuelto cuando se cierre #14

**Comment by guillermo-k** [comment]
Solucionado junto con #14
